version: 3.12
services:
  postgres:
    image: postgres:12-alpine
    ports:
    - '5432:5432'
    volumes:
    - ./var/lib/postgresql/data
   entrypoint:
     - POSTGRES_DB=app
       - POSTGRES_USER=app
       - POSTGRES_PASSWORD=qwerty123
